### ISSUE TITLE
7 images not working

### ISSUE THREAD

**Issue by MSchae1017** [joshpelkey/slack-countdown#23]
Below links aren't working

32 | http://www3.pictures.zimbio.com/gi/Andy+Teasdall+PlayStation+Fiesta+Bowl+Ohio+KUGrUzm1rbul.jpg
35 | https://www.gastongazette.com/storyimage/NC/20180719/SPORTS/180718030/AR/0/AR-180718030.jpg
39 | http://www3.pictures.zimbio.com/gi/Chandler+Catanzaro+Chick+fil+Bowl+LSU+v+Clemson+mcqlin-l0fhl.jpg
40 | http://www4.pictures.zimbio.com/gi/Darrell+Smith+Clemson+v+North+Carolina+State+1O6rtSMtes4l.jpg
60 | https://media.gettyimages.com/photos/jesse-pickens-of-the-clemson-tigers-rests-betweeen-plays-during-a-picture-id53567178
66 | https://www.goupstate.com/storyimage/NC/20050605/News/605169641/AR/0/AR-605169641.jpg
75 | https://images2.minutemediacdn.com/image/upload/c_fillw_912h_516f_autoq_autog_auto/shape/cover/sport/cfp-national-championship-5bdde43404bc97a939000008.jpg

**Comment by joshpelkey** [comment]
merged PR
